### ISSUE TITLE
Upgrade peer dependency to @babel/core 7

### ISSUE THREAD

**Issue by amithgeorge** [Andarist/babel-plugin-annotate-pure-calls#13]
Currently when using this plugin in a project that has @babel/core v7 installed, we get the following warning message 

```
npm WARN babel-plugin-annotate-pure-calls@0.3.0 requires a peer of babel-core@6.x || ^7.0.0-0 but none is installed. You must install peer dependencies yourself.
```

Agreed, it is only a warning. Though it would be nice if you could fix it.

**Comment by Andarist** [comment]
I've just released 0.4.0 which should address this for babel@7, but will cause the same problem for babel@6. In both cases the issue is solvable by installing a bridge version of the babel-core (or @babel/core), like described [here](https://github.com/Andarist/babel-plugin-annotate-pure-calls#usage-with-babel6).

Let me know if everything is OK.
